### ISSUE TITLE
Travis Build badge on readme is not working

### ISSUE THREAD

**Issue by mtscout6** [eslint-plugins/eslint-plugin-lean-imports#1]
<img width="435" alt="screen shot 2015-07-24 at 7 57 49 pm" src="https://cloud.githubusercontent.com/assets/736870/8887415/4fda59c0-323e-11e5-8488-6f1a7fce4809.png">

@dozoisch You have the permission to set that up on travis if you have a minute.

**Comment by dozoisch** [comment]
Alright, I'll set it up!

**Comment by dozoisch** [comment]
should be fix by next push
