### ISSUE TITLE
warn when install 

### ISSUE THREAD

**Issue by ChinaXing** [eslint-plugins/eslint-plugin-lean-imports#7]
/usr/local/lib
├── UNMET PEER DEPENDENCY eslint@>=2.0.0
└── eslint-plugin-lean-imports@0.3.3 

npm WARN eslint-plugin-lean-imports@0.3.3 requires a peer of eslint@>=2.0.0 but none was installed.

lambda-cat.local ➜  static git:(ha) eslint --version
v3.12.2

**Comment by dozoisch** [comment]
That's really weird because it should match 3.0 too since the range is >2.0.0. Is your eslint installed globally or locally?
